#!/bin/bash

# precompile assets
# rails assets:precompile -q -s

# download the codeclimate test reporter
curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
chmod +x ./cc-test-reporter

# start codeclimate test reporter
./cc-test-reporter before-build
